# Generated by Django 2.2.7 on 2019-12-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('unique_squirrel_id', models.CharField(help_text="'Hectare ID'+'Shift'+'Date'+'Hectare Squirrel Number'", max_length=100)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('date', models.DateField()),
                ('age', models.CharField(blank=True, choices=[('AD', 'Adult'), ('JU', 'Juvenile')], max_length=10)),
                ('primary_fur_color', models.CharField(blank=True, choices=[('GR', 'Gray'), ('CI', 'Cinnamon'), ('BL', 'Black')], max_length=10)),
                ('location', models.CharField(blank=True, choices=[('GP', 'Ground Plane'), ('AG', 'Above Ground')], max_length=20)),
                ('specific_location', models.CharField(blank=True, max_length=100)),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('foraging', models.BooleanField()),
                ('other_activities', models.CharField(blank=True, max_length=100)),
                ('kuks', models.BooleanField()),
                ('quaas', models.BooleanField()),
                ('moans', models.BooleanField()),
                ('tail_flags', models.BooleanField()),
                ('tail_twitches', models.BooleanField()),
                ('approaches', models.BooleanField()),
                ('indifferent', models.BooleanField()),
                ('runs_from', models.BooleanField()),
            ],
        ),
    ]
